import type { FloorplanMeasurement } from "@/lib/floorplans/types";
import { imageProvenance } from "@/lib/floorplans/sample-evidence-fixtures";

export const floorplanMeasurements: FloorplanMeasurement[] = [
  {
    id: "m-one-floor",
    subjectType: "level",
    subjectKey: "main-floor",
    subjectLabel: "Main floor",
    measurementType: "unknown",
    kind: "known",
    status: "active",
    displayValue: "1 floor",
    confidence: "high",
    provenance: [imageProvenance.overview],
  },
  {
    id: "m-interior-wall-thickness",
    subjectType: "plan",
    subjectKey: "main-floor",
    subjectLabel: "Main floor wall model",
    measurementType: "wallThickness",
    kind: "assumption",
    status: "active",
    valueIn: 4.5,
    minIn: 3.5,
    maxIn: 6,
    displayValue: "4.5 in assumed interior walls",
    confidence: "medium",
    provenance: [
      {
        ...imageProvenance.overview,
        id: "prov-wall-thickness-assumption",
        sourceType: "calculation",
        notes:
          "The sketches show walls but do not label wall thickness; reserve a typical interior wall band so rooms cannot consume all visible space.",
      },
    ],
  },
  {
    id: "m-official-conditioned-area-superseded",
    subjectType: "plan",
    subjectKey: "scott-house",
    subjectLabel: "Scott house",
    measurementType: "conditionedArea",
    kind: "assumption",
    status: "superseded",
    unit: "sqft",
    value: 1800,
    displayValue: "1,800 sq ft superseded sample assumption",
    confidence: "low",
    areaRole: "conditioned",
    constraintStrength: "displayOnly",
    provenance: [
      {
        ...imageProvenance.overview,
        id: "prov-official-conditioned-area-superseded",
        sourceType: "textNote",
        sourceLabel: "Superseded placeholder square-footage assumption",
        notes:
          "This was a generic sample target. The user later supplied 2013 sq ft, which supersedes this assumption.",
      },
    ],
  },
  {
    id: "m-official-conditioned-area",
    subjectType: "plan",
    subjectKey: "scott-house",
    subjectLabel: "Scott house",
    measurementType: "conditionedArea",
    kind: "known",
    status: "active",
    unit: "sqft",
    value: 2013,
    displayValue: "2,013 sq ft listed conditioned area",
    confidence: "high",
    areaRole: "conditioned",
    constraintStrength: "strong",
    provenance: [
      {
        ...imageProvenance.userFacts,
        id: "prov-official-conditioned-area-2013",
        notes:
          "Authoritative correction from the user. Patio, carport, workshop, and shed are excluded from this house-area target.",
      },
    ],
  },
  {
    id: "m-lot-area-superseded",
    subjectType: "lot",
    subjectKey: "lot",
    subjectLabel: "Property lot",
    measurementType: "lotArea",
    kind: "assumption",
    status: "superseded",
    unit: "acre",
    value: 0.25,
    displayValue: "0.25 acre superseded lot assumption",
    confidence: "low",
    areaRole: "outdoor",
    constraintStrength: "displayOnly",
    provenance: [
      {
        ...imageProvenance.overview,
        id: "prov-lot-area-assumption-superseded",
        sourceType: "textNote",
        sourceLabel: "Superseded placeholder property context",
        notes:
          "The user later supplied 9540 sq ft, which supersedes this generic lot assumption.",
      },
    ],
  },
  {
    id: "m-lot-area",
    subjectType: "lot",
    subjectKey: "lot",
    subjectLabel: "Property lot",
    measurementType: "lotArea",
    kind: "known",
    status: "active",
    unit: "sqft",
    value: 9540,
    displayValue: "9,540 sq ft listed lot size",
    confidence: "high",
    areaRole: "outdoor",
    constraintStrength: "strong",
    provenance: [
      {
        ...imageProvenance.userFacts,
        id: "prov-lot-area-9540",
        notes:
          "Authoritative lot-size correction from the user, used as the property-frame target.",
      },
    ],
  },
  {
    id: "m-garage-excluded-area-superseded",
    subjectType: "structure",
    subjectKey: "garage",
    subjectLabel: "Garage",
    measurementType: "excludedArea",
    kind: "assumption",
    status: "superseded",
    unit: "sqft",
    value: 440,
    displayValue: "20 ft x 22 ft superseded garage assumption",
    confidence: "low",
    areaRole: "excluded",
    constraintStrength: "displayOnly",
    provenance: [
      {
        ...imageProvenance.overview,
        id: "prov-garage-excluded-area-superseded",
        sourceType: "calculation",
        sourceLabel: "Superseded excluded-area assumption",
        notes:
          "The satellite/user correction says this property has a bottom-left carport, plus a workshop and shed, rather than the sample garage block.",
      },
    ],
  },
  {
    id: "m-carport-excluded-area",
    subjectType: "structure",
    subjectKey: "carport",
    subjectLabel: "Carport",
    measurementType: "excludedArea",
    kind: "known",
    status: "active",
    unit: "sqft",
    value: 300,
    minValue: 240,
    maxValue: 420,
    displayValue: "bottom-left carport excluded; area estimated 240-420 sq ft",
    confidence: "medium",
    areaRole: "excluded",
    constraintStrength: "strong",
    provenance: [
      {
        ...imageProvenance.satellite,
        id: "prov-carport-excluded-area",
        notes:
          "Satellite view and user note identify the bottom-left covered carport as excluded from the 2013 sq ft house area.",
      },
      {
        ...imageProvenance.userFacts,
        id: "prov-carport-user-exclusion",
        notes: "User explicitly said the carport is not part of square footage.",
      },
    ],
  },
  {
    id: "m-workshop-excluded-area",
    subjectType: "structure",
    subjectKey: "workshop",
    subjectLabel: "Workshop",
    measurementType: "excludedArea",
    kind: "known",
    status: "active",
    unit: "sqft",
    value: 480,
    minValue: 360,
    maxValue: 650,
    displayValue: "top-left workshop excluded; area estimated 360-650 sq ft",
    confidence: "medium",
    areaRole: "excluded",
    constraintStrength: "strong",
    provenance: [
      {
        ...imageProvenance.satellite,
        id: "prov-workshop-excluded-area",
        notes:
          "Satellite view and user correction identify the large top-left detached building as a workshop excluded from house square footage.",
      },
    ],
  },
  {
    id: "m-shed-excluded-area",
    subjectType: "structure",
    subjectKey: "shed",
    subjectLabel: "Shed",
    measurementType: "excludedArea",
    kind: "known",
    status: "active",
    unit: "sqft",
    value: 180,
    minValue: 120,
    maxValue: 260,
    displayValue: "top-left shed excluded; area estimated 120-260 sq ft",
    confidence: "medium",
    areaRole: "excluded",
    constraintStrength: "strong",
    provenance: [
      {
        ...imageProvenance.satellite,
        id: "prov-shed-excluded-area",
        notes:
          "Satellite view and user correction identify the smaller top-left detached building as a shed excluded from house square footage.",
      },
    ],
  },
  {
    id: "m-patio-excluded-area",
    subjectType: "zone",
    subjectKey: "back-patio",
    subjectLabel: "Rear patio / pool deck",
    measurementType: "excludedArea",
    kind: "known",
    status: "active",
    unit: "sqft",
    value: 1200,
    minValue: 900,
    maxValue: 1600,
    displayValue: "large rear patio / pool deck excluded; area estimated 900-1,600 sq ft",
    confidence: "medium",
    areaRole: "excluded",
    constraintStrength: "strong",
    provenance: [
      {
        ...imageProvenance.satellite,
        id: "prov-patio-excluded-area",
        notes:
          "User said most of the bright rear satellite area is patio and not counted in the 2013 sq ft house total.",
      },
      {
        ...imageProvenance.userFacts,
        id: "prov-patio-user-exclusion",
        notes: "User explicitly excluded patio from listed house square footage.",
      },
    ],
  },
  {
    id: "m-bonus-width",
    subjectType: "room",
    subjectKey: "bonus-room",
    subjectLabel: "Bonus room",
    measurementType: "width",
    kind: "known",
    status: "active",
    valueIn: ft(25),
    displayValue: "25 ft",
    confidence: "high",
    provenance: [imageProvenance.bonus],
  },
  {
    id: "m-bonus-depth",
    subjectType: "room",
    subjectKey: "bonus-room",
    subjectLabel: "Bonus room",
    measurementType: "depth",
    kind: "known",
    status: "active",
    valueIn: ft(13),
    displayValue: "13 ft",
    confidence: "high",
    provenance: [imageProvenance.bonus],
  },
  {
    id: "m-bonus-height",
    subjectType: "room",
    subjectKey: "bonus-room",
    subjectLabel: "Bonus room",
    measurementType: "height",
    kind: "known",
    status: "active",
    valueIn: ft(9),
    displayValue: "9 ft ceiling",
    confidence: "high",
    provenance: [imageProvenance.bonus],
  },
  {
    id: "m-front-living-width",
    subjectType: "room",
    subjectKey: "front-living",
    subjectLabel: "Front living room",
    measurementType: "width",
    kind: "known",
    status: "active",
    valueIn: ft(24),
    displayValue: "24 ft",
    confidence: "high",
    provenance: [imageProvenance.frontKitchen],
  },
  {
    id: "m-front-living-depth",
    subjectType: "room",
    subjectKey: "front-living",
    subjectLabel: "Front living room",
    measurementType: "depth",
    kind: "known",
    status: "active",
    valueIn: ft(17.5),
    displayValue: "17.5 ft",
    confidence: "high",
    provenance: [imageProvenance.frontKitchen],
  },
  {
    id: "m-laundry-width",
    subjectType: "room",
    subjectKey: "laundry",
    subjectLabel: "Laundry / washery",
    measurementType: "width",
    kind: "known",
    status: "active",
    valueIn: ft(10),
    displayValue: "10 ft",
    confidence: "high",
    provenance: [imageProvenance.laundry],
  },
  {
    id: "m-laundry-side-run",
    subjectType: "room",
    subjectKey: "laundry",
    subjectLabel: "Laundry / washery",
    measurementType: "depth",
    kind: "known",
    status: "active",
    valueIn: ft(6),
    displayValue: "6 ft side run",
    confidence: "high",
    provenance: [imageProvenance.laundry],
  },
  {
    id: "m-kitchen-entry",
    subjectType: "opening",
    subjectKey: "bonus-kitchen-entry",
    subjectLabel: "Bonus room to kitchen entry",
    measurementType: "openingWidth",
    kind: "known",
    status: "active",
    valueIn: 66,
    displayValue: "66 in entry",
    confidence: "high",
    provenance: [imageProvenance.bonus, imageProvenance.frontKitchen],
  },
  {
    id: "m-kitchen-width-assumption",
    subjectType: "room",
    subjectKey: "kitchen",
    subjectLabel: "Kitchen",
    measurementType: "width",
    kind: "assumption",
    status: "active",
    valueIn: ft(20),
    minIn: ft(17),
    maxIn: ft(22),
    displayValue: "about 20 ft",
    confidence: "medium",
    provenance: [
      {
        ...imageProvenance.frontKitchen,
        id: "prov-kitchen-width-assumption",
        sourceType: "calculation",
        notes:
          "Estimated from measured front living span plus visible counter and hall relationships.",
      },
    ],
  },
  {
    id: "m-kitchen-depth-assumption",
    subjectType: "room",
    subjectKey: "kitchen",
    subjectLabel: "Kitchen",
    measurementType: "depth",
    kind: "assumption",
    status: "active",
    valueIn: ft(12.5),
    minIn: ft(11),
    maxIn: ft(14),
    displayValue: "about 12.5 ft",
    confidence: "medium",
    provenance: [
      {
        ...imageProvenance.frontKitchen,
        id: "prov-kitchen-depth-assumption",
        sourceType: "calculation",
        notes:
          "Estimated from fixture runs and the 66 in entry relationship; needs one outside wall measurement.",
      },
    ],
  },
  {
    id: "m-hall-width-assumption",
    subjectType: "path",
    subjectKey: "hall",
    subjectLabel: "Hall",
    measurementType: "depth",
    kind: "assumption",
    status: "active",
    valueIn: ft(4.5),
    minIn: ft(3),
    maxIn: ft(6),
    displayValue: "3-6 ft clear hall width, drawn at 4 ft 6 in",
    confidence: "medium",
    provenance: [
      imageProvenance.overview,
      {
        ...imageProvenance.hallCrop,
        id: "prov-hall-width-range",
        notes:
          "The crop confirms hall orientation and continuity, but not an exact width.",
      },
    ],
  },
  {
    id: "m-hall-length-assumption",
    subjectType: "path",
    subjectKey: "hall",
    subjectLabel: "Hall",
    measurementType: "width",
    kind: "assumption",
    status: "active",
    valueIn: ft(20),
    minIn: ft(16),
    maxIn: ft(24),
    displayValue: "about 20 ft left-to-right hall run",
    confidence: "medium",
    provenance: [
      {
        ...imageProvenance.hallCrop,
        id: "prov-hall-horizontal-run",
        notes:
          "User correction and crop establish this as the one left-to-right hall; length remains approximate.",
      },
    ],
  },
  {
    id: "m-right-bath-walled-block",
    subjectType: "room",
    subjectKey: "bath-1",
    subjectLabel: "Right-wing bathroom",
    measurementType: "unknown",
    kind: "known",
    status: "active",
    displayValue: "walled bathroom block, dimensions not yet measured",
    confidence: "high",
    provenance: [
      {
        ...imageProvenance.rightBathroomCrop,
        id: "prov-right-bath-walled-block",
        notes:
          "Crop shows the bathroom outline as a complete room with walls, so the solver must reserve a real room block.",
      },
    ],
  },
  {
    id: "m-room-1-width-derived",
    subjectType: "room",
    subjectKey: "room-1",
    subjectLabel: "Room 1",
    measurementType: "width",
    kind: "derived",
    status: "active",
    valueIn: ft(20.5),
    minIn: ft(19),
    maxIn: ft(23),
    displayValue: "about 20 ft 6 in, derived from area reconciliation",
    confidence: "medium",
    provenance: [
      {
        ...imageProvenance.overview,
        id: "prov-room-1-overview",
        notes: "Overview sketch labels Room 1 below the kitchen.",
      },
      {
        ...imageProvenance.userFacts,
        id: "prov-room-1-area-reconciliation-width",
        sourceType: "calculation",
        notes:
          "The 2013 sq ft target leaves a missing conditioned-area block; Room 1 is the visible omitted room that best explains it.",
      },
    ],
    derivedFromMeasurementIds: ["m-official-conditioned-area"],
  },
  {
    id: "m-room-1-depth-derived",
    subjectType: "room",
    subjectKey: "room-1",
    subjectLabel: "Room 1",
    measurementType: "depth",
    kind: "derived",
    status: "active",
    valueIn: ft(18.25),
    minIn: ft(16),
    maxIn: ft(20),
    displayValue: "about 18 ft 3 in, derived from area reconciliation",
    confidence: "medium",
    provenance: [
      {
        ...imageProvenance.overview,
        id: "prov-room-1-depth-overview",
        notes: "Overview sketch shows Room 1 below kitchen and left of the bedroom wing.",
      },
      {
        ...imageProvenance.userFacts,
        id: "prov-room-1-area-reconciliation-depth",
        sourceType: "calculation",
        notes:
          "Derived size preserves measured rooms while bringing solved conditioned area close to the 2013 sq ft listed target.",
      },
    ],
    derivedFromMeasurementIds: ["m-official-conditioned-area"],
  },
  {
    id: "m-room-2-range",
    subjectType: "room",
    subjectKey: "room-2",
    subjectLabel: "Room 2",
    measurementType: "width",
    kind: "range",
    status: "active",
    minIn: ft(12),
    maxIn: ft(16),
    displayValue: "12-16 ft assumed range",
    confidence: "low",
    provenance: [imageProvenance.overview],
  },
  {
    id: "m-room-3-range",
    subjectType: "room",
    subjectKey: "room-3",
    subjectLabel: "Room 3",
    measurementType: "width",
    kind: "range",
    status: "active",
    minIn: ft(12),
    maxIn: ft(16),
    displayValue: "12-16 ft assumed range",
    confidence: "low",
    provenance: [imageProvenance.overview],
  },
];

function ft(value: number) {
  return value * 12;
}
