import type {
  FloorplanObservation,
  FloorplanRelationship,
} from "@/lib/floorplans/types";
import {
  buildFloorplanSubjects,
  createDraftStateFromEvidence,
  gapPrioritiesFromEvidence,
} from "@/lib/floorplans/evidence-engine";
import { imageProvenance } from "@/lib/floorplans/sample-evidence-fixtures";
import { floorplanMeasurements } from "@/lib/floorplans/sample-measurement-fixtures";

export const floorplanObservations: FloorplanObservation[] = [
  {
    id: "obs-front-living-label",
    observationType: "roomName",
    status: "active",
    title: "Front living room label",
    subjectKey: "front-living",
    subjectLabel: "Front living room",
    subjectKind: "room",
    rawText: "FRONT LIVING ROOM",
    normalized: { roomName: "Front living room" },
    confidence: "high",
    sourceResourceId: "front-kitchen-detail",
    sourceLabel: imageProvenance.frontKitchen.sourceLabel,
    imageNumber: imageProvenance.frontKitchen.imageNumber,
    relatedMeasurementIds: ["m-front-living-width", "m-front-living-depth"],
    provenance: [imageProvenance.frontKitchen],
  },
  {
    id: "obs-front-living-dims",
    observationType: "measurementText",
    status: "active",
    title: "Front living measured 24 ft by 17.5 ft",
    subjectKey: "front-living",
    subjectLabel: "Front living room",
    subjectKind: "room",
    rawText: "24 ft, 17 1/2 ft",
    normalized: { widthFt: 24, depthFt: 17.5 },
    confidence: "high",
    sourceResourceId: "front-kitchen-detail",
    sourceLabel: imageProvenance.frontKitchen.sourceLabel,
    imageNumber: imageProvenance.frontKitchen.imageNumber,
    relatedMeasurementIds: ["m-front-living-width", "m-front-living-depth"],
    provenance: [imageProvenance.frontKitchen],
  },
  {
    id: "obs-bonus-room-label",
    observationType: "roomName",
    status: "active",
    title: "Bonus room label",
    subjectKey: "bonus-room",
    subjectLabel: "Bonus room",
    subjectKind: "room",
    rawText: "BONUS ROOM",
    normalized: { roomName: "Bonus room" },
    confidence: "high",
    sourceResourceId: "bonus-detail",
    sourceLabel: imageProvenance.bonus.sourceLabel,
    imageNumber: imageProvenance.bonus.imageNumber,
    relatedMeasurementIds: ["m-bonus-width", "m-bonus-depth", "m-bonus-height"],
    provenance: [imageProvenance.bonus],
  },
  {
    id: "obs-bonus-room-dims",
    observationType: "measurementText",
    status: "active",
    title: "Bonus room measured 25 ft by 13 ft",
    subjectKey: "bonus-room",
    subjectLabel: "Bonus room",
    subjectKind: "room",
    rawText: "25 ft, 13 ft, 9 ft ceilings",
    normalized: { widthFt: 25, depthFt: 13, ceilingFt: 9 },
    confidence: "high",
    sourceResourceId: "bonus-detail",
    sourceLabel: imageProvenance.bonus.sourceLabel,
    imageNumber: imageProvenance.bonus.imageNumber,
    relatedMeasurementIds: ["m-bonus-width", "m-bonus-depth", "m-bonus-height"],
    provenance: [imageProvenance.bonus],
  },
  {
    id: "obs-laundry-label",
    observationType: "roomName",
    status: "active",
    title: "Laundry / washery label",
    subjectKey: "laundry",
    subjectLabel: "Laundry / washery",
    subjectKind: "room",
    rawText: "LAUNDRY / WASHERY",
    normalized: { roomName: "Laundry / washery" },
    confidence: "high",
    sourceResourceId: "laundry-detail",
    sourceLabel: imageProvenance.laundry.sourceLabel,
    imageNumber: imageProvenance.laundry.imageNumber,
    relatedMeasurementIds: ["m-laundry-width", "m-laundry-side-run"],
    provenance: [imageProvenance.laundry],
  },
  {
    id: "obs-kitchen-label",
    observationType: "roomName",
    status: "active",
    title: "Kitchen label and fixture run",
    subjectKey: "kitchen",
    subjectLabel: "Kitchen",
    subjectKind: "kitchen",
    rawText: "KITCHEN, cabinets, stove, window, sink",
    normalized: { roomName: "Kitchen", fixtures: "stove, window, sink, cabinets" },
    confidence: "medium",
    sourceResourceId: "front-kitchen-detail",
    sourceLabel: imageProvenance.frontKitchen.sourceLabel,
    imageNumber: imageProvenance.frontKitchen.imageNumber,
    relatedMeasurementIds: ["m-kitchen-width-assumption", "m-kitchen-depth-assumption"],
    provenance: [imageProvenance.frontKitchen, imageProvenance.livingKitchenHall],
  },
  {
    id: "obs-hall-horizontal",
    observationType: "hall",
    status: "active",
    title: "One horizontal hall",
    subjectKey: "hall",
    subjectLabel: "Hall",
    subjectKind: "hall",
    rawText: "HALL ->",
    normalized: { orientation: "left-to-right", count: 1 },
    confidence: "high",
    sourceResourceId: "hall-crop",
    sourceLabel: imageProvenance.hallCrop.sourceLabel,
    imageNumber: imageProvenance.hallCrop.imageNumber,
    relatedMeasurementIds: ["m-hall-width-assumption", "m-hall-length-assumption"],
    notes:
      "User correction: this is the one hall in the house and it runs left-to-right.",
    provenance: [imageProvenance.hallCrop, imageProvenance.livingKitchenHall],
  },
  {
    id: "obs-room-1-label",
    observationType: "roomName",
    status: "active",
    title: "Room 1 label",
    subjectKey: "room-1",
    subjectLabel: "Room 1",
    subjectKind: "room",
    rawText: "Room 1",
    normalized: { roomName: "Room 1" },
    confidence: "medium",
    sourceResourceId: "overview",
    sourceLabel: imageProvenance.overview.sourceLabel,
    imageNumber: imageProvenance.overview.imageNumber,
    relatedMeasurementIds: ["m-room-1-width-derived", "m-room-1-depth-derived"],
    provenance: [imageProvenance.overview, imageProvenance.frontKitchen],
  },
  {
    id: "obs-room-2-label",
    observationType: "roomName",
    status: "active",
    title: "Room 2 label",
    subjectKey: "room-2",
    subjectLabel: "Room 2",
    subjectKind: "room",
    rawText: "Room 2",
    normalized: { roomName: "Room 2" },
    confidence: "medium",
    sourceResourceId: "overview",
    sourceLabel: imageProvenance.overview.sourceLabel,
    imageNumber: imageProvenance.overview.imageNumber,
    relatedMeasurementIds: ["m-room-2-range"],
    provenance: [imageProvenance.overview],
  },
  {
    id: "obs-room-3-label",
    observationType: "roomName",
    status: "active",
    title: "Room 3 label",
    subjectKey: "room-3",
    subjectLabel: "Room 3",
    subjectKind: "room",
    rawText: "Room 3",
    normalized: { roomName: "Room 3" },
    confidence: "medium",
    sourceResourceId: "overview",
    sourceLabel: imageProvenance.overview.sourceLabel,
    imageNumber: imageProvenance.overview.imageNumber,
    relatedMeasurementIds: ["m-room-3-range"],
    provenance: [imageProvenance.overview],
  },
  {
    id: "obs-right-bath-walled",
    observationType: "roomName",
    status: "active",
    title: "Right-wing bathroom is walled",
    subjectKey: "right-bath",
    subjectLabel: "Right-wing bathroom",
    subjectKind: "bathroom",
    rawText: "BATHROOM",
    normalized: { roomName: "Bathroom", hasBoundaryWalls: true },
    confidence: "high",
    sourceResourceId: "right-bathroom-crop",
    sourceLabel: imageProvenance.rightBathroomCrop.sourceLabel,
    imageNumber: imageProvenance.rightBathroomCrop.imageNumber,
    relatedMeasurementIds: ["m-right-bath-walled-block"],
    notes:
      "User correction: this is all a bathroom and it has a wall; do not model it as a loose fixture.",
    provenance: [imageProvenance.rightBathroomCrop, imageProvenance.overview],
  },
  {
    id: "obs-kitchen-window",
    observationType: "window",
    status: "active",
    title: "Kitchen window on counter wall",
    subjectKey: "kitchen-window",
    subjectLabel: "Kitchen window",
    subjectKind: "opening",
    rawText: "WINDOW",
    normalized: { openingType: "window", hostRoom: "kitchen" },
    confidence: "medium",
    sourceResourceId: "front-kitchen-detail",
    sourceLabel: imageProvenance.frontKitchen.sourceLabel,
    imageNumber: imageProvenance.frontKitchen.imageNumber,
    provenance: [imageProvenance.frontKitchen],
  },
  {
    id: "obs-doorless-hall-passages",
    observationType: "doorlessPassage",
    status: "active",
    title: "Hall wall breaks may be doorless passages",
    subjectKey: "hall-passages",
    subjectLabel: "Hall passages",
    subjectKind: "opening",
    rawText: "wall breaks without door swing arcs",
    normalized: { openingType: "passage", doorSwingConfirmed: false },
    confidence: "medium",
    sourceResourceId: "hall-crop",
    sourceLabel: imageProvenance.hallCrop.sourceLabel,
    imageNumber: imageProvenance.hallCrop.imageNumber,
    notes:
      "Doorway without a swing proves connection, not a hinged door. The solver should keep this distinction.",
    provenance: [imageProvenance.hallCrop, imageProvenance.overview],
  },
  {
    id: "obs-official-area-2013",
    observationType: "areaTarget",
    status: "active",
    title: "Listed house square footage",
    subjectKey: "scott-house",
    subjectLabel: "Scott house",
    subjectKind: "structure",
    rawText: "2013 sq/ft",
    normalized: { conditionedSqFt: 2013 },
    confidence: "high",
    sourceResourceId: "user-area-facts",
    sourceLabel: imageProvenance.userFacts.sourceLabel,
    relatedMeasurementIds: ["m-official-conditioned-area"],
    provenance: [imageProvenance.userFacts],
  },
  {
    id: "obs-lot-area-9540",
    observationType: "areaTarget",
    status: "active",
    title: "Listed lot size",
    subjectKey: "lot",
    subjectLabel: "Property lot",
    subjectKind: "lot",
    rawText: "9540 sq/ft lot",
    normalized: { lotSqFt: 9540 },
    confidence: "high",
    sourceResourceId: "user-area-facts",
    sourceLabel: imageProvenance.userFacts.sourceLabel,
    relatedMeasurementIds: ["m-lot-area"],
    provenance: [imageProvenance.userFacts],
  },
  {
    id: "obs-carport-excluded",
    observationType: "carport",
    status: "active",
    title: "Bottom-left carport excluded from house sqft",
    subjectKey: "carport",
    subjectLabel: "Carport",
    subjectKind: "structure",
    rawText: "carport bottom left; not part of sqft",
    normalized: { areaRole: "excluded", location: "bottom-left" },
    confidence: "high",
    sourceResourceId: "satellite-property",
    sourceLabel: imageProvenance.satellite.sourceLabel,
    imageNumber: imageProvenance.satellite.imageNumber,
    relatedMeasurementIds: ["m-carport-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
  {
    id: "obs-workshop-excluded",
    observationType: "exteriorStructure",
    status: "active",
    title: "Top-left workshop excluded from house sqft",
    subjectKey: "workshop",
    subjectLabel: "Workshop",
    subjectKind: "structure",
    rawText: "workshop top left; not part of sqft",
    normalized: { areaRole: "excluded", location: "top-left" },
    confidence: "high",
    sourceResourceId: "satellite-property",
    sourceLabel: imageProvenance.satellite.sourceLabel,
    imageNumber: imageProvenance.satellite.imageNumber,
    relatedMeasurementIds: ["m-workshop-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
  {
    id: "obs-shed-excluded",
    observationType: "shed",
    status: "active",
    title: "Top-left shed excluded from house sqft",
    subjectKey: "shed",
    subjectLabel: "Shed",
    subjectKind: "structure",
    rawText: "shed top left; not part of sqft",
    normalized: { areaRole: "excluded", location: "top-left" },
    confidence: "high",
    sourceResourceId: "satellite-property",
    sourceLabel: imageProvenance.satellite.sourceLabel,
    imageNumber: imageProvenance.satellite.imageNumber,
    relatedMeasurementIds: ["m-shed-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
  {
    id: "obs-patio-pool-excluded",
    observationType: "patio",
    status: "active",
    title: "Rear patio and pool deck excluded from house sqft",
    subjectKey: "back-patio",
    subjectLabel: "Rear patio / pool deck",
    subjectKind: "zone",
    rawText: "patio / pool area not house sqft",
    normalized: { areaRole: "excluded", location: "rear" },
    confidence: "high",
    sourceResourceId: "satellite-property",
    sourceLabel: imageProvenance.satellite.sourceLabel,
    imageNumber: imageProvenance.satellite.imageNumber,
    relatedMeasurementIds: ["m-patio-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
];

export const floorplanRelationships: FloorplanRelationship[] = [
  {
    id: "rel-front-living-kitchen",
    relationshipType: "connectedTo",
    status: "active",
    fromSubjectKey: "front-living",
    fromSubjectLabel: "Front living room",
    toSubjectKey: "kitchen",
    toSubjectLabel: "Kitchen",
    confidence: "medium",
    sourceObservationIds: ["obs-front-living-label", "obs-kitchen-label"],
    notes: "Overview and detail sketches show the living room leading toward the kitchen side.",
    provenance: [imageProvenance.overview, imageProvenance.frontKitchen],
  },
  {
    id: "rel-kitchen-bonus",
    relationshipType: "connectedTo",
    status: "active",
    fromSubjectKey: "kitchen",
    fromSubjectLabel: "Kitchen",
    toSubjectKey: "bonus-room",
    toSubjectLabel: "Bonus room",
    confidence: "high",
    sourceObservationIds: ["obs-bonus-room-label", "obs-kitchen-label"],
    sourceMeasurementIds: ["m-kitchen-entry"],
    notes: "The 66 in entry connects the bonus room/kitchen side.",
    provenance: [imageProvenance.bonus, imageProvenance.frontKitchen],
  },
  {
    id: "rel-kitchen-hall",
    relationshipType: "connectedTo",
    status: "active",
    fromSubjectKey: "kitchen",
    fromSubjectLabel: "Kitchen",
    toSubjectKey: "hall",
    toSubjectLabel: "Hall",
    confidence: "high",
    sourceObservationIds: ["obs-kitchen-label", "obs-hall-horizontal"],
    notes: "The kitchen detail points to the hall direction.",
    provenance: [imageProvenance.livingKitchenHall, imageProvenance.hallCrop],
  },
  {
    id: "rel-hall-room-1",
    relationshipType: "connectedTo",
    status: "active",
    fromSubjectKey: "hall",
    fromSubjectLabel: "Hall",
    toSubjectKey: "room-1",
    toSubjectLabel: "Room 1",
    confidence: "medium",
    sourceObservationIds: ["obs-hall-horizontal", "obs-room-1-label"],
    provenance: [imageProvenance.overview, imageProvenance.livingKitchenHall],
  },
  {
    id: "rel-hall-room-2",
    relationshipType: "connectedTo",
    status: "active",
    fromSubjectKey: "hall",
    fromSubjectLabel: "Hall",
    toSubjectKey: "room-2",
    toSubjectLabel: "Room 2",
    confidence: "medium",
    sourceObservationIds: ["obs-hall-horizontal", "obs-room-2-label"],
    provenance: [imageProvenance.overview, imageProvenance.hallCrop],
  },
  {
    id: "rel-hall-room-3",
    relationshipType: "connectedTo",
    status: "active",
    fromSubjectKey: "hall",
    fromSubjectLabel: "Hall",
    toSubjectKey: "room-3",
    toSubjectLabel: "Room 3",
    confidence: "medium",
    sourceObservationIds: ["obs-hall-horizontal", "obs-room-3-label"],
    provenance: [imageProvenance.overview, imageProvenance.hallCrop],
  },
  {
    id: "rel-hall-right-bath",
    relationshipType: "connectedTo",
    status: "active",
    fromSubjectKey: "hall",
    fromSubjectLabel: "Hall",
    toSubjectKey: "right-bath",
    toSubjectLabel: "Right-wing bathroom",
    confidence: "high",
    sourceObservationIds: ["obs-hall-horizontal", "obs-right-bath-walled"],
    notes: "Bathroom access should resolve from the horizontal hall/wing, not a floating fixture.",
    provenance: [imageProvenance.rightBathroomCrop, imageProvenance.hallCrop],
  },
  {
    id: "rel-kitchen-window-opening",
    relationshipType: "openingIn",
    status: "active",
    fromSubjectKey: "kitchen-window",
    fromSubjectLabel: "Kitchen window",
    toSubjectKey: "kitchen",
    toSubjectLabel: "Kitchen",
    confidence: "medium",
    sourceObservationIds: ["obs-kitchen-window"],
    notes: "The window must attach to the kitchen counter wall before geometry generation.",
    provenance: [imageProvenance.frontKitchen],
  },
  {
    id: "rel-hall-passages-opening",
    relationshipType: "doorlessPassageBetween",
    status: "active",
    fromSubjectKey: "hall-passages",
    fromSubjectLabel: "Hall passages",
    toSubjectKey: "hall",
    toSubjectLabel: "Hall",
    confidence: "medium",
    sourceObservationIds: ["obs-doorless-hall-passages", "obs-hall-horizontal"],
    notes: "The evidence proves openings; door swings are not confirmed.",
    provenance: [imageProvenance.hallCrop, imageProvenance.overview],
  },
  {
    id: "rel-carport-excluded-area",
    relationshipType: "excludedFromArea",
    status: "active",
    fromSubjectKey: "carport",
    fromSubjectLabel: "Carport",
    toSubjectKey: "scott-house",
    toSubjectLabel: "Scott house",
    confidence: "high",
    sourceObservationIds: ["obs-carport-excluded"],
    sourceMeasurementIds: ["m-carport-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
  {
    id: "rel-workshop-excluded-area",
    relationshipType: "excludedFromArea",
    status: "active",
    fromSubjectKey: "workshop",
    fromSubjectLabel: "Workshop",
    toSubjectKey: "scott-house",
    toSubjectLabel: "Scott house",
    confidence: "high",
    sourceObservationIds: ["obs-workshop-excluded"],
    sourceMeasurementIds: ["m-workshop-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
  {
    id: "rel-shed-excluded-area",
    relationshipType: "excludedFromArea",
    status: "active",
    fromSubjectKey: "shed",
    fromSubjectLabel: "Shed",
    toSubjectKey: "scott-house",
    toSubjectLabel: "Scott house",
    confidence: "high",
    sourceObservationIds: ["obs-shed-excluded"],
    sourceMeasurementIds: ["m-shed-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
  {
    id: "rel-patio-excluded-area",
    relationshipType: "excludedFromArea",
    status: "active",
    fromSubjectKey: "back-patio",
    fromSubjectLabel: "Rear patio / pool deck",
    toSubjectKey: "scott-house",
    toSubjectLabel: "Scott house",
    confidence: "high",
    sourceObservationIds: ["obs-patio-pool-excluded"],
    sourceMeasurementIds: ["m-patio-excluded-area"],
    provenance: [imageProvenance.satellite, imageProvenance.userFacts],
  },
];

export const floorplanSubjects = buildFloorplanSubjects({
  observations: floorplanObservations,
  relationships: floorplanRelationships,
  measurements: floorplanMeasurements,
});

export const sampleFloorplanDraftState = createDraftStateFromEvidence({
  observations: floorplanObservations,
  relationships: floorplanRelationships,
  measurements: floorplanMeasurements,
});

export const evidenceFirstGapPriorities = gapPrioritiesFromEvidence({
  observations: floorplanObservations,
  relationships: floorplanRelationships,
  measurements: floorplanMeasurements,
});
