import { ConvexError } from "convex/values";

import type { Doc } from "../_generated/dataModel";
import { visibilityForHouseholdRole, type HouseholdRole } from "./roles";

export const ACCOUNT_EXPORT_EXPIRATION_MS = 14 * 24 * 60 * 60 * 1000;
export const ACCOUNT_DELETION_GRACE_MS = 7 * 24 * 60 * 60 * 1000;
export const ACCOUNT_DELETION_CONFIRMATION = "DELETE MY ACCOUNT";

export const retentionPolicy = {
  accountExports:
    "Account export artifacts expire after 14 days and can be regenerated by the signed-in user.",
  generatedMoveExports:
    "Generated move/documentation exports expire after 30 days by default.",
  deletion:
    "Account deletion is staged for 7 days, then disables and anonymizes the user profile while preserving household records owned by other collaborators.",
  accessRevocation:
    "Deletion completion revokes API keys and share links created by the deleting user and disables that user's memberships and move-level grants.",
  auditLogs:
    "Audit logs are retained for security and abuse investigation with the user profile anonymized instead of hard-deleted.",
  queueHistory:
    "Queue items and attributable activity remain with the move so collaborators retain the work record; account deletion anonymizes the user profile and revokes that person's AI access.",
  storage:
    "Photo objects are retained with their household/move records unless a household owner deletes the source records or a future storage cleanup job removes archived data.",
} as const;

export function accountExportExpiresAt(now: number) {
  return now + ACCOUNT_EXPORT_EXPIRATION_MS;
}

export function accountDeletionScheduledAt(now: number) {
  return now + ACCOUNT_DELETION_GRACE_MS;
}

export function accountExportFilename(now: number) {
  const date = new Date(now).toISOString().slice(0, 10);
  return `movingmanifest-account-export-${date}.json`;
}

export function anonymizedUserPatch(now: number) {
  return {
    email: undefined,
    name: "Deleted user",
    imageUrl: undefined,
    status: "disabled" as const,
    defaultHouseholdId: undefined,
    updatedAt: now,
    lastSeenAt: now,
  };
}

export function assertDeletionConfirmation(value: string) {
  if (value !== ACCOUNT_DELETION_CONFIRMATION) {
    throw new ConvexError(`Type ${ACCOUNT_DELETION_CONFIRMATION} to confirm deletion.`);
  }
}

export function redactItemForExport(
  item: Doc<"items">,
  role: HouseholdRole
) {
  const visibility = visibilityForHouseholdRole(role);

  return {
    id: item._id,
    moveId: item.moveId,
    name: item.name,
    description: item.description,
    room: item.room,
    destinationRoom: item.destinationRoom,
    category: item.category,
    subcategory: item.subcategory,
    disposition: item.disposition,
    status: item.status,
    quantity: item.quantity,
    condition: item.condition,
    valueCents: visibility.estimatedValue ? item.valueCents : undefined,
    replacementValueCents: visibility.purchaseValue
      ? item.replacementValueCents
      : undefined,
    serialNumber: visibility.serialNumber ? item.serialNumber : undefined,
    modelNumber: visibility.serialNumber ? item.modelNumber : undefined,
    estimatedWeightLb: item.estimatedWeightLb,
    actualWeightLb: item.actualWeightLb,
    estimatedVolumeCuFt: item.estimatedVolumeCuFt,
    fragility: item.fragility,
    hazardousFlag: item.hazardousFlag,
    highValue: item.highValue,
    requiresPersonalTransport: item.requiresPersonalTransport,
    planningDefaultKeys: item.planningDefaultKeys,
    needsReview: item.needsReview,
    reviewFlags: item.reviewFlags,
    privateNotes: visibility.privateNotes ? item.privateNotes : undefined,
    createdVia: item.createdVia,
    createdAt: item.createdAt,
    updatedAt: item.updatedAt,
    deletedAt: item.deletedAt,
  };
}

export function summarizeExportPackage(packageData: {
  households: unknown[];
  moves: unknown[];
  items: unknown[];
  boxes: unknown[];
  photos: unknown[];
  exportJobs: unknown[];
  apiKeys: unknown[];
  shareLinks: unknown[];
  queueItems: unknown[];
  queueActivities: unknown[];
}) {
  return {
    households: packageData.households.length,
    moves: packageData.moves.length,
    items: packageData.items.length,
    boxes: packageData.boxes.length,
    photos: packageData.photos.length,
    exportJobs: packageData.exportJobs.length,
    apiKeys: packageData.apiKeys.length,
    shareLinks: packageData.shareLinks.length,
    queueItems: packageData.queueItems.length,
    queueActivities: packageData.queueActivities.length,
  };
}
