export const restRouteManifest = [
  route("GET", "/me", ["moves/read"], "API key context"),
  route("GET", "/exports/{exportId}", ["exports/read"], "Top-level export lookup"),
  route("GET", "/items/{itemId}", ["inventory/read"], "Top-level item lookup"),
  route("PATCH", "/items/{itemId}", ["inventory/write"], "Top-level item update"),
  route("DELETE", "/items/{itemId}", ["inventory/write"], "Top-level item archive"),
  route("GET", "/boxes/{boxId}", ["inventory/read"], "Top-level box lookup"),
  route("PATCH", "/boxes/{boxId}", ["inventory/write"], "Top-level box update"),
  route("POST", "/boxes/{boxId}/items", ["inventory/write"], "Assign item to box"),
  route("DELETE", "/boxes/{boxId}/items/{itemId}", ["inventory/write"], "Remove item from box"),
  route("POST", "/photos/{photoId}/attach", ["photos/write"], "Attach or update photo metadata"),
  route("GET", "/photos/{photoId}/display-url", ["inventory/read"], "Signed photo display URL"),
  route("GET", "/images/{photoId}/display-url", ["inventory/read"], "Signed image display URL alias"),
  route("POST", "/uploads/init", ["photos/write"], "Initialize multipart media upload"),
  route("POST", "/photos/upload", ["photos/write"], "Direct photo upload"),
  route("POST", "/images/upload", ["photos/write"], "Direct image upload alias"),
  route("POST", "/photos/finalize", ["photos/write"], "Finalize multipart media upload"),
  route("GET", "/plans", ["plans/read"], "List floor plans"),
  route("POST", "/plans", ["plans/write"], "Create floor plan"),
  route("GET", "/plans/{planId}", ["plans/read"], "Get floor plan document"),
  route("GET", "/plans/{planId}/summary", ["plans/read"], "Get floor plan summary"),
  route("GET", "/plans/{planId}/snapshot.svg", ["plans/read"], "Get floor plan SVG snapshot"),
  route("POST", "/plans/{planId}/ops", ["plans/write"], "Apply floor plan operations"),
  route("GET", "/plans/{planId}/proposals", ["plans/read"], "List floor plan proposals"),
  route("POST", "/plans/{planId}/proposals", ["plans/write"], "Create floor plan proposal"),
  route("GET", "/plans/{planId}/floorplan-evidence", ["plans/read"], "List floorplan evidence and measurements"),
  route("POST", "/plans/{planId}/floorplan-evidence", ["plans/write"], "Create floorplan evidence and measurements"),
  route("PATCH", "/plans/{planId}/floorplan-evidence/{evidenceId}", ["plans/write"], "Update floorplan evidence"),
  route("POST", "/plans/{planId}/floorplan-evidence/{evidenceId}/supersede", ["plans/write"], "Supersede floorplan evidence"),
  route("POST", "/plans/{planId}/floorplan-solve", ["plans/write"], "Validate and solve floorplan constraints"),
  route("GET", "/households/{householdId}/members", ["members/manage"], "List household members"),
  route("POST", "/households/{householdId}/members", ["members/manage"], "Invite household member"),
  route("GET", "/moves", ["moves/read"], "List moves"),
  route("POST", "/moves", ["moves/write"], "Create move"),
  route("POST", "/moves/setup", ["moves/read", "moves/write", "inventory/write"], "Set up move"),
  route("GET", "/moves/{moveId}", ["moves/read"], "Get move"),
  route("PATCH", "/moves/{moveId}", ["moves/write"], "Update move"),
  route("GET", "/moves/{moveId}/summary", ["moves/read", "inventory/read", "exports/read"], "Get move summary"),
  route("GET", "/moves/{moveId}/questions", ["moves/read", "inventory/read"], "Get move questions"),
  route("GET", "/moves/{moveId}/move-day", ["moves/read", "inventory/read"], "Get move-day checklist"),
  route("GET", "/moves/{moveId}/capacity-report", ["moves/read", "inventory/read"], "Get capacity report"),
  route("GET", "/moves/{moveId}/agent-context", ["moves/read", "inventory/read", "plans/read"], "Get agent context"),
  route("GET", "/moves/{moveId}/spaces", ["moves/read"], "List move spaces"),
  route("POST", "/moves/{moveId}/spaces", ["moves/write"], "Create move space"),
  route("PATCH", "/moves/{moveId}/spaces/{spaceId}", ["moves/write"], "Update move space"),
  route("PUT", "/moves/{moveId}/spaces/{spaceId}", ["moves/write"], "Replace move space"),
  route("GET", "/moves/{moveId}/sale-listings", ["inventory/read"], "List sale listings"),
  route("POST", "/moves/{moveId}/sale-listings", ["inventory/write"], "Create sale listing"),
  route("PATCH", "/moves/{moveId}/sale-listings/{listingId}", ["inventory/write"], "Update sale listing"),
  route("PUT", "/moves/{moveId}/sale-listings/{listingId}", ["inventory/write"], "Replace sale listing"),
  route("GET", "/moves/{moveId}/resources", ["inventory/read"], "List transport resources"),
  route("POST", "/moves/{moveId}/resources", ["inventory/write"], "Create transport resource"),
  route("GET", "/moves/{moveId}/resources/{resourceId}", ["inventory/read"], "Get transport resource"),
  route("PATCH", "/moves/{moveId}/resources/{resourceId}", ["inventory/write"], "Update transport resource"),
  route("GET", "/moves/{moveId}/resources/{resourceId}/zones", ["inventory/read"], "List resource zones"),
  route("POST", "/moves/{moveId}/resources/{resourceId}/zones", ["inventory/write"], "Create resource zone"),
  route("GET", "/moves/{moveId}/zones", ["inventory/read"], "List transport zones"),
  route("POST", "/moves/{moveId}/zones", ["inventory/write"], "Create transport zone"),
  route("GET", "/moves/{moveId}/zones/{zoneId}", ["inventory/read"], "Get transport zone"),
  route("PATCH", "/moves/{moveId}/zones/{zoneId}", ["inventory/write"], "Update transport zone"),
  route("GET", "/moves/{moveId}/people", ["moves/read"], "List move people"),
  route("POST", "/moves/{moveId}/people", ["moves/write"], "Create move person"),
  route("GET", "/moves/{moveId}/people/{personId}", ["moves/read"], "Get move person"),
  route("PATCH", "/moves/{moveId}/people/{personId}", ["moves/write"], "Update move person"),
  route("DELETE", "/moves/{moveId}/people/{personId}", ["moves/write"], "Archive move person"),
  route("GET", "/moves/{moveId}/items", ["inventory/read"], "List inventory items"),
  route("POST", "/moves/{moveId}/items", ["inventory/write"], "Create inventory item"),
  route("GET", "/moves/{moveId}/items/{itemId}", ["inventory/read"], "Get inventory item"),
  route("PATCH", "/moves/{moveId}/items/{itemId}", ["inventory/write"], "Update inventory item"),
  route("POST", "/moves/{moveId}/items/batch-upsert", ["inventory/write"], "Batch upsert inventory items"),
  route("GET", "/moves/{moveId}/planned-items", ["inventory/read"], "List planned items"),
  route("POST", "/moves/{moveId}/planned-items", ["inventory/write"], "Create planned item"),
  route("GET", "/moves/{moveId}/planned-items/{plannedItemId}", ["inventory/read"], "Get planned item"),
  route("PATCH", "/moves/{moveId}/planned-items/{plannedItemId}", ["inventory/write"], "Update planned item"),
  route("DELETE", "/moves/{moveId}/planned-items/{plannedItemId}", ["inventory/write"], "Archive planned item"),
  route("POST", "/moves/{moveId}/planned-items/{plannedItemId}/convert", ["inventory/write"], "Convert planned item"),
  route("GET", "/moves/{moveId}/boxes", ["inventory/read"], "List boxes"),
  route("POST", "/moves/{moveId}/boxes", ["inventory/write"], "Create box"),
  route("GET", "/moves/{moveId}/boxes/{boxId}", ["inventory/read"], "Get box"),
  route("PATCH", "/moves/{moveId}/boxes/{boxId}", ["inventory/write"], "Update box"),
  route("POST", "/moves/{moveId}/boxes/{boxId}/items", ["inventory/write"], "Assign item to move box"),
  route("PUT", "/moves/{moveId}/boxes/{boxId}/items", ["inventory/write"], "Upsert item assignment to move box"),
  route("DELETE", "/moves/{moveId}/boxes/{boxId}/items", ["inventory/write"], "Remove item assignments from move box"),
  route("POST", "/moves/{moveId}/box-items", ["inventory/write"], "Batch assign box items"),
  route("PUT", "/moves/{moveId}/box-items", ["inventory/write"], "Batch upsert box items"),
  route("DELETE", "/moves/{moveId}/box-items", ["inventory/write"], "Batch remove box items"),
  route("GET", "/moves/{moveId}/assignments", ["inventory/read"], "List assignments"),
  route("POST", "/moves/{moveId}/assignments", ["inventory/write"], "Create assignment"),
  route("PUT", "/moves/{moveId}/assignments", ["inventory/write"], "Upsert assignment"),
  route("DELETE", "/moves/{moveId}/assignments/{assignmentId}", ["inventory/write"], "Delete assignment"),
  route("POST", "/moves/{moveId}/assignments/suggest", ["inventory/write"], "Suggest assignments"),
  route("POST", "/moves/{moveId}/assignments/apply", ["inventory/write"], "Apply assignments"),
  route("GET", "/moves/{moveId}/planning-suggestions", ["inventory/read"], "List planning suggestions"),
  route("GET", "/moves/{moveId}/planning-suggestions/{suggestionId}", ["inventory/read"], "Get planning suggestion"),
  route("POST", "/moves/{moveId}/planning-suggestions/generate", ["inventory/write"], "Generate planning suggestions"),
  route("POST", "/moves/{moveId}/planning-suggestions/approve", ["inventory/write"], "Approve planning suggestions"),
  route("POST", "/moves/{moveId}/planning-suggestions/reject", ["inventory/write"], "Reject planning suggestions"),
  route("GET", "/moves/{moveId}/ai-jobs", ["inventory/read"], "List AI jobs"),
  route("GET", "/moves/{moveId}/ai-jobs/{aiJobId}", ["inventory/read"], "Get AI job"),
  route("GET", "/moves/{moveId}/ai-jobs/provider-status", ["inventory/read"], "Get AI provider status"),
  route("GET", "/moves/{moveId}/ai-text-suggestions", ["inventory/read"], "List AI text suggestions"),
  route("GET", "/moves/{moveId}/ai-text-suggestions/{suggestionId}", ["inventory/read"], "Get AI text suggestion"),
  route("POST", "/moves/{moveId}/ai-text-suggestions/generate", ["inventory/write"], "Generate AI text suggestions"),
  route("POST", "/moves/{moveId}/ai-text-suggestions/approve", ["inventory/write"], "Approve AI text suggestions"),
  route("POST", "/moves/{moveId}/ai-text-suggestions/reject", ["inventory/write"], "Reject AI text suggestions"),
  route("GET", "/moves/{moveId}/ai-photo-suggestions", ["inventory/read"], "List AI photo suggestions"),
  route("GET", "/moves/{moveId}/ai-photo-suggestions/{suggestionId}", ["inventory/read"], "Get AI photo suggestion"),
  route("POST", "/moves/{moveId}/ai-photo-suggestions/generate", ["inventory/write"], "Generate AI photo suggestions"),
  route("POST", "/moves/{moveId}/ai-photo-suggestions/approve", ["inventory/write"], "Approve AI photo suggestions"),
  route("POST", "/moves/{moveId}/ai-photo-suggestions/reject", ["inventory/write"], "Reject AI photo suggestions"),
  route("GET", "/moves/{moveId}/ingestion-queue", ["inventory/read"], "List ingestion queue"),
  route("POST", "/moves/{moveId}/ingestion-queue", ["inventory/write"], "Create ingestion queue entry"),
  route("POST", "/moves/{moveId}/ingestion-queue/claim", ["inventory/write"], "Claim ingestion queue entries"),
  route("POST", "/moves/{moveId}/ingestion-queue/{entryId}/results", ["inventory/write"], "Submit ingestion results"),
  route("POST", "/moves/{moveId}/ingestion-queue/{entryId}/status", ["inventory/write"], "Update ingestion entry status"),
  route("GET", "/moves/{moveId}/ingestion-queue/{entryId}/evidence/{photoId}/url", ["inventory/read"], "Get ingestion evidence URL"),
  route("GET", "/moves/{moveId}/documentation-profiles", ["exports/read"], "List documentation profiles"),
  route("POST", "/moves/{moveId}/documentation-profiles", ["exports/create"], "Create documentation profile"),
  route("GET", "/moves/{moveId}/documentation-profiles/{documentationProfileId}", ["exports/read"], "Get documentation profile"),
  route("PATCH", "/moves/{moveId}/documentation-profiles/{documentationProfileId}", ["exports/create"], "Update documentation profile"),
  route("DELETE", "/moves/{moveId}/documentation-profiles/{documentationProfileId}", ["exports/create"], "Archive documentation profile"),
  route("POST", "/moves/{moveId}/documentation-profiles/{documentationProfileId}/archive", ["exports/create"], "Archive documentation profile"),
  route("GET", "/moves/{moveId}/exports", ["exports/read"], "List export jobs"),
  route("POST", "/moves/{moveId}/exports", ["exports/create"], "Create export job"),
  route("GET", "/moves/{moveId}/exports/{exportJobId}", ["exports/read"], "Get export job"),
  route("GET", "/moves/{moveId}/exports/{exportJobId}/download", ["exports/read"], "Get export artifact"),
  route("GET", "/moves/{moveId}/share-links", ["exports/read"], "List share links"),
  route("POST", "/moves/{moveId}/share-links", ["exports/create"], "Create share link"),
  route("GET", "/moves/{moveId}/share-links/comments", ["exports/read"], "List move share comments"),
  route("GET", "/moves/{moveId}/share-links/{shareLinkId}", ["exports/read"], "Get share link"),
  route("GET", "/moves/{moveId}/share-links/{shareLinkId}/comments", ["exports/read"], "List share link comments"),
  route("DELETE", "/moves/{moveId}/share-links/{shareLinkId}", ["exports/create"], "Revoke share link"),
  route("POST", "/moves/{moveId}/share-links/{shareLinkId}/revoke", ["exports/create"], "Revoke share link"),
  route("GET", "/moves/{moveId}/photos", ["inventory/read"], "List move photos"),
];

export const contractEnumManifest = {
  itemDisposition: ["undecided", "take", "sell", "donate", "dump", "free", "storage", "mover", "personalTransport"],
  itemFragility: ["low", "medium", "high"],
  confidence: ["none", "low", "medium", "high", "manual", "actual", "estimated"],
  ingestionQueueStatus: ["queued", "claimed", "processed", "needsInput", "resolved", "discarded"],
  ingestionScopeHint: ["inventory", "packing", "condition", "measurements", "floorPlan"],
  photoDerivativeVariant: ["thumb", "card", "detail", "full"],
};

function route(method, pathPattern, scopes, description) {
  return { method, pathPattern, scopes, description };
}
